---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/pages/index.mdx
  label: Home Page
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "*.mdx"
  exclude: 404.js
  new_doc_ext: mdx
  templates:
  - normal-page
- type: directory
  path: src/pages/posts
  label: Blog
  create: documents
  match: "*.mdx"
  exclude: "*.test.mdx"
  new_doc_ext: mdx
upload_dir: ''
public_path: https://r3-images.s3.amazonaws.com
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
