# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Vercel Deployment
      uses: xmflsct/action-vercel-deployment@v0.5.3
      with:
        # Your token at Vercel. See https://vercel.com/account/tokens
        vercelToken: 6bdnAXjF1WtshAKdThWwoT7T
        vercelOrgId: 5foApRXa3Qotva2qqamiVrfH
        # Your Project ID at Vercel.
        vercelProjectId: QmagisqyNrJGGjYZ188j66yXzicmm9vXmaegc4uDGWQDRD
        # Your token at GitHub. See https://github.com/settings/tokens
        githubToken: 173cf7c7d3c390966c35dcfd1c2600d5eda70791
